### ISSUE TITLE
bugs and updates

### ISSUE THREAD

**Issue by drikssy** [Debond-Protocol/Debond-ERC3475#6]
- [x] Check if the amount is > 0 when we issue

- [x] in Issue function, get the require to != address(0) out of the for loop

- [x] we probably don't need to keep in storage all the nonceIds for a class

- [x] maybe put every allowance conditions in transferFrom (NOT NEEDED!)

- [x] in the redeem function, we need to make sure that the redeemer is the one who is calling the function 

- [x] maybe find a way to get the collateral to another address (redeem process)

- [x] create some events for nonce Creation (NOT NEEDED!)

**Comment by Yohjisakamoto** [comment]
**maybe find a way to get the collateral to another address (redeem process)**
When you redeemed, you can choice to which address you want to redeem your bonds, both the interest and collateral will be returned to that address.

 **we probably don't need to keep in storage all the nonceIds for a class**
Yes like we discussed, the new update dont need them. it was there because we forgot to delete them.

 **maybe put every allowance conditions in transferFrom**
I think we have two functions transfer from and transfer allowance, when we want to transfer allowance is the transfer allowance is called. if we call transfer from means we transfer our own bonds, or of an address that we have the authorization to do so.

**create some events for nonce Creation:**
We don't need this, because we consider a nonce created only when the first bond is issued. and the event of the first bond issued can be captured as the nonce created. If we just want to update some metadata or values of a nonce, we dont need an event I think.

**Comment by yuliu-debond** [comment]
**maybe find a way to get the collateral to another address (redeem process)**
When you redeemed, you can choice to which address you want to redeem your bonds, both the interest and collateral will be returned to that address.

 **we probably don't need to keep in storage all the nonceIds for a class**
Yes like we discussed, the new update dont need them. it was there because we forgot to delete them.

 **maybe put every allowance conditions in transferFrom**
I think we have two functions transfer from and transfer allowance, when we want to transfer allowance is the transfer allowance is called. if we call transfer from means we transfer our own bonds, or of an address that we have the authorization to do so.

**create some events for nonce Creation:**
We don't need this, because we consider a nonce created only when the first bond is issued. and the event of the first bond issued can be captured as the nonce created. If we just want to update some metadata or values of a nonce, we dont need an event I think.

**Comment by drikssy** [comment]
> maybe find a way to get the collateral to another address (redeem process)
When you redeemed, you can choice to which address you want to redeem your bonds, both the interest and collateral will be returned to that address.

So in the redeem function (implementation of IERC3475) can we consider that the from is the address we want to send the collateral to? @yuliu-debond

**Comment by Yohjisakamoto** [comment]
I think the redeem function have a _to address

**Comment by drikssy** [comment]
> maybe find a way to get the collateral to another address (redeem process)

I think we might have an issue implementing this through the bond...
the redeem function has 2 inputs parameters (from the IERC3475) from and Transactions![Capture du 2022-10-03 18-09-09.png](https://images.zenhubusercontent.com/621e277daeddc35b7b9df91b/7b377a34-bb13-4acd-b45e-5e29921a7f25)

in the same function in our debondERC3475, we are calling the Bank to send back the collateral to that from address...
Given the IERC3475 interface signature, we won't be able to add the "to" address input to know who to send the collateral to

**Comment by dhruvmalik007** [comment]
can you maybe override this @drikssy with another function  (delegateRedeem, or redemptionTo) ?

**Comment by drikssy** [comment]
@dhruvmalik007 if we do this it will not be able to be called through IERC3475 interface by external front dapps

**Comment by Yohjisakamoto** [comment]
Yes,

**Comment by Yohjisakamoto** [comment]
I think the _to is not necessary here.

**Comment by Yohjisakamoto** [comment]
sorry for my previous mistakes
